server:
  port: 8001


spring:
  application:
    name: cloud-payment-service     # 服务名
  # 数据源定义
  datasource:
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.microservice.entities


eureka:
  instance:
    instance-id: payment-service-1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka

